### PR TITLE
Support repeating keys.

### LINKED ISSUE #8: Add key-repeat functionality.
If a non-meta key is held down, repeat it after a time delay.

Default to a delay of 500ms, then the held down key is repeated every 30ms thereafter.

### PR DESCRIPTION
**Pull request by ezrec**
- Fixes #8 

- Movement keys (Up-Down-Left-Right)
- CTRL-Z (repeating undo)
- Tab
- Backspace
- Enter
- Any printable key.

### CODE REVIEW

**Comment by healeycodes** [comment]
Hey @ezrec, this is a great idea!

Code looks good.


I noticed a small bug while testing.

Holding down any of `ctrl+x`, `ctrl+c`, or `ctrl+v`, acts kinda strangely.

On the first tick, after the initial action, the letter starts being entered when I would expect a repeated action – e.g. multiple pastes, re-copying (but no visual change), for cutting I guess nothing should happen after the first action.

(I think cutting with nothing selected should delete the line but that's out of scope)

If the character is `a`, it will paste `avvvvv` (the copied character, followed by a bunch of `v`s.

**Comment by ezrec** [comment]
> Holding down any of `ctrl+x`, `ctrl+c`, or `ctrl+v`, acts kinda strangely.

Good catches!  I found some other issues with Option/Meta/Control/Shift and believe I've also addressed those, check to make sure I didn't break any semantics on MacOS.

**Comment by healeycodes** [comment]
> > Holding down any of `ctrl+x`, `ctrl+c`, or `ctrl+v`, acts kinda strangely.
> 
> Good catches! I found some other issues with Option/Meta/Control/Shift and believe I've also addressed those, check to make sure I didn't break any semantics on MacOS.

The existing issues I saw are gone but I've found something new (or didn't find it when I tested earlier).

It seems like cmd+arrows isn't snapping to the end of the line/end of the document (I'm testing this on macOS but I suspect it's on all platforms).

Some kind of test suite to catch this stuff would help (I just added an issue for input tests: https://github.com/healeycodes/noter/issues/10).

**Comment by ezrec** [comment]
Yeah, I'm at a loss as to how to provide a good input injecting testcase for the Editor.Update()

However, I've redone the logic in the shift/command/option key handing to try to make it clearer what's going on and under what conditions the key is expected to function in.

**Comment by healeycodes** [comment]
Looks great! No issues in my local testing.

This is a wonderful change. Thanks @ezrec!

I'll approve and merge.

**Review by healeycodes — APPROVED** [review]
👍

**Pull request merged**
