### PR TITLE
Separate Editor struct from noter application

### PR DESCRIPTION
**Pull request by ezrec**
Some improvements, while I was at it:

- Document external functions
- Add support for font.Face style fonts (both monospace and proportional)
- Use 'option function' idiom for specifying options
- top and bottom bars are now optional
- Overridable Clipboard support (see cmd/noter/main.go for system clipboard example)

### CODE REVIEW

**Comment by healeycodes** [comment]
Hi @ezrec!

This looks great. I'm excited to merge it but just want to run it first.

I'm having an issue testing it locally on my Mac.

Here's what I run into:

```
go run github.com/healeycodes/noter/cmd/noter -- "A Bird, came down the Walk.txt"
# github.com/healeycodes/noter/cmd/noter
ld: warning: '/private/var/folders/61/lbcm8sq51g7fjcvsk6hhz0q00000gn/T/go-link-3283385633/go.o' has malformed LC_DYSYMTAB, expected 72 undefined symbols to start at index 8324, found 196 undefined symbols starting at index 93
panic: purego: fn is nil

goroutine 1 [running]:
github.com/ebitengine/purego.SyscallN(0x14000026001?, {0x0?, 0x1400013da58?, 0x100727d8c?})
	/Users/andrew/go/pkg/mod/github.com/ebitengine/purego@v0.0.0-20220905075623-aeed57cda744/syscall.go:29 +0xc4
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/metal/mtl.CreateSystemDefaultDevice()
	/Users/andrew/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.16/internal/graphicsdriver/metal/mtl/mtl_darwin.go:553 +0x34
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/metal.init.0()
	/Users/andrew/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.16/internal/graphicsdriver/metal/graphics_darwin.go:336 +0x1c
exit status 2
```

```
go version
go version go1.19.1 darwin/arm64
```


Same error when building.

**Comment by ezrec** [comment]
What do you get with:

`CGO_ENABLED=1  go run ./cmd/noter`

(I'm also running go v1.19, but on Linux)

It looks like ebitengine is crashing in it's library's init() for initializing the MacOS Metal display interface, which I believe happens before `main()` is even called.

I assume your main branch still works with no issue?

**Comment by healeycodes** [comment]
> What do you get with:
> 
> `CGO_ENABLED=1 go run ./cmd/noter`

Same error

> (I'm also running go v1.19, but on Linux)
> 
> It looks like ebitengine is crashing in it's library's init() for initializing the MacOS Metal display interface, which I believe happens before `main()` is even called.
> 
> I assume your main branch still works with no issue?

Ah, thanks for the suggestion. I get the same error on my main branch. I bumped the engine version and the error went away! Strange. Thanks for helping me debug that.

**Comment by healeycodes** [comment]
Everything works for me locally!

No issues in my manual testing 👍

**Comment by ezrec** [comment]
Land whenever you are ready - I don't have permission to do so.

**Comment by healeycodes** [comment]
@ezrec 👋 

I had another read through of the code and the organization looks great.

I couldn't alter font-size via flags. Or by manually altering the default value. Perhaps it's not implemented yet? Will merge anyway as nothing existing is broken.

Thanks again!

**Comment by ezrec** [comment]
What `-font` did you specify when trying the `-fontsize` and `-fontdpi` options?

The 'default' font is an ebitengine bitmap font, which is a fixed size, and therefore those options do nothing unless `-font` is specified. (I should have made the help text clearer about that!)

**Comment by healeycodes** [comment]
> What `-font` did you specify when trying the `-fontsize` and `-fontdpi` options?
> 
> The 'default' font is an ebitengine bitmap font, which is a fixed size, and therefore those options do nothing unless `-font` is specified. (I should have made the help text clearer about that!)

Ah yes. I just tried `-fontsize` without adding a font. Your explanation here makes sense, thanks!

**Pull request merged**
