### PR TITLE
Issue 15 keyboard movement

### LINKED ISSUE #15: Keyboard movement updates
- PageUp/PageDown should move by page.
- Cursor down at bottom of visible page should scroll up by single line, not page.
- Cursor up at top of visible page should scroll down by single line, not page.
- Home should go to beginning of line.
- End should go to end of line.

### PR DESCRIPTION
**Pull request by ezrec**
- Fixes #15 

Adds support for
* Home/End to start and end of line
* SHIFT-Home  and SHIFT-End highlighting
* PageUp/PageDown movement
* Scroll by line for arrow up/down at outside of viewable area.

### CODE REVIEW

**Comment by ezrec** [comment]
Let me know if there are any issues with your keymap, only tested on US-QWERTY.

**Comment by healeycodes** [comment]
@ezrec one thing I just ran into while testing. If you go to the end of a document and hold down Enter (e.g. insert 40 new lines), then the cursor ends up out of view. If you then type, you are typing off screen.

**Comment by ezrec** [comment]
Addressed - also fixed an issue where COMMAND-RIGHT_ARROW was being ignored

**Comment by healeycodes** [comment]
Works great! Code is good too 👍

**Review by healeycodes — APPROVED** [review]
👍

**Pull request merged**
